MoviesListFilter
mate-academy/react_movies-list-filter-js pull request #156
Opened 2023-07-27 14:17 UTC by Dmytro-Tymchenko

[DEMO LINK](https://Dmytro-Tymchenko.github.io/react_movies-list-filter-js/)

2023-07-27 17:02 UTC, Viktor-Kost requested changes
Nice!
Some minor fixes needed

2023-07-27 17:02 UTC, Viktor-Kost commented on src/components/MoviesList/MoviesList.jsx
> +  const visibleMovies = movies.filter((movie) => {
The formattedQuery is being calculated on each iteration of the filter function which can affect performance. You can calculate the formattedQuery outside of the filter function to increase performance.

also if you're familiar with useMemo hook it'd be nice to apply it here

2023-07-28 08:21 UTC, Dmytro-Tymchenko commented on src/components/MoviesList/MoviesList.jsx
> +  const visibleMovies = movies.filter((movie) => {
I haven't worked with useMemo yet

2023-07-28 12:28 UTC, IvanFesenko approved these changes
Approved. But take a note from my comment

2023-07-28 12:28 UTC, IvanFesenko commented on src/components/MoviesList/MoviesList.jsx
> +
Recomendation: No need to filter in case when query is empty

2025-08-08 08:15 UTC, closed without merging