feat: add task solution
mate-academy/react_movies-list-filter-js pull request #219
Opened 2023-08-24 11:40 UTC by FrontKid

[DEMO LINK](https://Frontkid.github.io/react_movies-list-filter-js/)

2023-08-28 12:54 UTC, StasSokolov commented on src/utils/movieUtils.js
> +        = description.toLowerCase().includes(queryToLowerCase);
you use same methods `.toLowerCase().includes(...)`, will be good to create separated helper function for this logic

2023-08-28 12:59 UTC, StasSokolov requested changes
Good! Please deploy your solution and add a demo link to the PR description

2023-08-29 15:07 UTC, Valentyn-Bilyk approved these changes

2023-08-29 17:58 UTC, dffUqp approved these changes
GJ✔️

2023-08-29 17:58 UTC, dffUqp commented on src/App.jsx
> +                onChange={event => setQuery(event.currentTarget.value)}
In `React` it is better to use `event.target`

[Difference between target and currentTarget](https://stackoverflow.com/questions/10086427/what-is-the-exact-difference-between-currenttarget-property-and-target-property)

2023-08-29 17:58 UTC, dffUqp commented on src/App.jsx
> +  const visibleMovies = getPreparedMovies(moviesFromServer, { query });
Why you put `query` inside object?

2025-07-29 13:59 UTC, closed without merging