add movies list filter by current searchbar query
mate-academy/react_movies-list-filter-js pull request #276
Opened 2023-08-29 21:07 UTC by neovendano

[DEMO LINK](https://neovendano.github.io/react_movies-list-filter-js/)

2023-08-31 16:14 UTC, vatatan approved these changes
Looks nice👌

2023-08-31 16:47 UTC, BudnikOleksii requested changes
Good work 👍 
Let's improve your solution a bit

2023-09-06 06:59 UTC, Moroz-Dmytro approved these changes

2023-09-06 06:59 UTC, Moroz-Dmytro commented on src/App.jsx
> +                }
```suggestion
                onChange={event => {
                  setQuery(event.target.value)
                }}
```

2023-09-06 06:59 UTC, Moroz-Dmytro commented on src/App.jsx
> +  const lowercasedQuery = query.toLowerCase();
```suggestion
  const lowercasedQuery = query.trim().toLowerCase();
```

2025-07-28 11:38 UTC, closed without merging